{
        # hyperparams for training
        "config2": {
                "architect_settings": 
                {
                        "model": "eff",
                        "n_cls": 10,
                        "n_conv": 2,
                        "Conv1": {"in": 1,
                                "out": 64,
                                "k": 5,
                                "s": 2,
                                "p": 0},
                        "Conv2": {"in": 64,
                                "out": 128,
                                "k": 5,
                                "s": 2,
                                "p": 0},
                        "PrimayCaps": {"in": 128,
                                "out": 32,
                                "k": 1,
                                "s": 1,
                                "p": 0},
                        "n_caps": 2,
                        "cap_dims": 4,
                        "Caps1": {"in": 32,
                                "out": 32,
                                "k": [3, 3],
                                "s": [2, 2]},
                        "Caps2": {"in": 32,
                                "out": 10,
                                "k": [3, 3],
                                "s": [1, 1]},
                        "routing": {"type": "dynamic",
                                "params" : [3]}
                },
                "training_settings":
                {
                        "loss": "spread",
                        "CAM": False,
                        "lr": 0.001,
                        "lr_step": 10,
                        "lr_decay": 0.8,
                        "momentum": 0.9,
                        "weight_decay": 0.005,
                        "n_epoch": 50,
                        "n_batch": 128,
                        "dataset": "affNist",
                        "ckpt_path": "test",
                }
        },
        # hyperparams for testing
        "demo-conv": {
                "architect_settings": 
                {
                        "model": "convolution",
                        "n_cls": 10,
                        "n_conv": 2,
                        "Conv1": {"in": 1,
                                "out": 64,
                                "k": 5,
                                "s": 2,
                                "p": 0},
                        "Conv2": {"in": 64,
                                "out": 128,
                                "k": 5,
                                "s": 2,
                                "p": 0},
                        "PrimayCaps": {"in": 128,
                                "out": 32,
                                "k": 1,
                                "s": 1,
                                "p": 0},
                        "n_caps": 2,
                        "cap_dims": 4,
                        "Caps1": {"in": 128,
                                "out": 32,
                                "k": [3, 3],
                                "s": [2, 2]},
                        "Caps2": {"in": 32,
                                "out": 10,
                                "k": [3, 3],
                                "s": [1, 1]},
                        "routing": {"type": "dynamic",
                                "params" : [3]}
                },
                "training_settings":{
                        "loss": "ce",
                        "CAM": True,
                        "ckpt_path": "model/test/conv.ckpt"
                }
        },

        "demo-cap1": {
                "architect_settings": 
                {
                        "model": "base",
                        "n_cls": 10,
                        "n_conv": 2,
                        "Conv1": {"in": 1,
                                "out": 64,
                                "k": 5,
                                "s": 2,
                                "p": 0},
                        "Conv2": {"in": 64,
                                "out": 128,
                                "k": 5,
                                "s": 2,
                                "p": 0},
                        "PrimayCaps": {"in": 128,
                                "out": 32,
                                "k": 1,
                                "s": 1,
                                "p": 0},
                        "n_caps": 2,
                        "cap_dims": 4,
                        "Caps1": {"in": 32,
                                "out": 32,
                                "k": [3, 3],
                                "s": [2, 2]},
                        "Caps2": {"in": 32,
                                "out": 10,
                                "k": [3, 3],
                                "s": [1, 1]},
                        "routing": {"type": "dynamic",
                                "params" : [3]}
                },
                "training_settings":{
                        "loss": "ce",
                        "CAM": True,
                        "ckpt_path": "model/test/base.ckpt"
                }
        },
        "demo-cap2": {
                "architect_settings": 
                {
                        "model": "eff",
                        "n_cls": 10,
                        "n_conv": 2,
                        "Conv1": {"in": 1,
                                "out": 64,
                                "k": 5,
                                "s": 2,
                                "p": 0},
                        "Conv2": {"in": 64,
                                "out": 128,
                                "k": 5,
                                "s": 2,
                                "p": 0},
                        "PrimayCaps": {"in": 128,
                                "out": 32,
                                "k": 1,
                                "s": 1,
                                "p": 0},
                        "n_caps": 2,
                        "cap_dims": 4,
                        "Caps1": {"in": 32,
                                "out": 32,
                                "k": [3, 3],
                                "s": [2, 2]},
                        "Caps2": {"in": 32,
                                "out": 10,
                                "k": [3, 3],
                                "s": [1, 1]},
                        "routing": {"type": "dynamic",
                                "params" : [3]}
                },
                "training_settings":{
                        "loss": "ce",
                        "CAM": True,
                        "ckpt_path": "model/test/eff-dynamic.ckpt"
                }
        },

}