{
        # hyperparams for training
        "config2": {
                "architect_settings" : {
                        "name": "eff-capsconv",
                        "reconstructed": True,
                        "n_cls": 10,
                        "convs": {
                                "channels": [1, 64, 128],
                                "k": 5,
                                "s": 2,
                                "p": 2},
                        "primay_caps": {
                                "channels": [128, 32],
                                "k": 3,
                                "s": 2,
                                "p": 1},
                        "caps": {
                                "init": "kaiming_uniform",
                                "cap_dims": 4,
                                "channels": [32, 16, 10],
                                "k": 3,
                                "s": 1,
                                "p": 0,
                                "routing": {
                                        "type": "em",
                                        "params" : [3]}}
                },
                "training_settings":
                {
                        "loss": "spread",
                        "CAM": False,
                        "lr": 0.001,
                        "lr_step": 10,
                        "lr_decay": 0.8,
                        "momentum": 0.9,
                        "weight_decay": 0.005,
                        "n_epoch": 50,
                        "n_batch": 128,
                        "dataset": "center-Mnist",
                        "ckpt_path": "test",
                }
        },
        
        "config-segment": {
                "architect_settings" : {
                        "name": "eff-capsUnet",
                        "reconstructed": False,
                        "channel": 1,
                        "n_filters": 6,
                        "n_layers": 5,
                        "conv": {
                                "k": 3,
                                "p": 1,
                                "s": 2
                        },
                        "transpose_conv": {
                                "k": 3,
                                "s": 2,
                                "p": 1
                        },
                        "caps":{
                                "init": "noisy_identity",
                                "cap_dims": 3,
                                "routing": {
                                "type": "dynamic",
                                "params" : [3]}
                        }
                },
                "training_settings":
                {
                        "loss": "dice",
                        "CAM": False,
                        "lr": 0.001,
                        "lr_step": 10,
                        "lr_decay": 0.8,
                        "momentum": 0.9,
                        "weight_decay": 0.005,
                        "n_epoch": 100,
                        "n_batch": 16,
                        "dataset": "CT-scan-dataset",
                        "ckpt_path": "test",
                }
        
        },
}