logger:
        project: kaori/Capsule-Network # replace with your own
        api_key: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIyZjZiMDA2YS02MDM3LTQxZjQtOTE4YS1jODZkMTJjNGJlMDYifQ== # replace with your own
        tags: None
task: classification # segmentation, classification
architect_settings:
        backbone:
                name: resnet-s
                is_backbone: false
                is_full: false
                is_pretrained: false
                is_freeze: true
        head:
                n_cls: 10
                n_layers: 2
                n_emb: 512
                is_caps: true # effective
                caps:
                        pooling: avg
                        reduce: false
                        cap_style: ortho # c: by channel, hw: by height and width, ortho: orthogonal porjection
                        cap_dims: 4
                        projection_type: 3D ## linear, ortho, 3D
                        routing:
                                type: dynamic # effective
                                iters: 3
                                temp: 1.5
dataset_settings:
        name: CIFAR10-feats # VOC2012, LungCT-Scan, CIFAR10, CIFAR100, Caltech101, CIFAR10-feats
        path: data/CIFAR10-features
        img_size: 224
training_settings: 
        gpu_ids: [0]
        n_gpu: 1
        loss: ce # spread < margin < ce
        metric: accuracy # dice, accuracy
        ckpt_path: "./mode/test"
        n_epoch: 100
        n_batch: 32
        num_workers: 0
        optimizer: adam
        lr_scheduler: step
        early_stopping: true
        lr: 0.0001 # not efective
        lr_step: 5
        lr_decay: 0.8
        momentum: 0.9
        weight_decay: 0.005