logger:
        project: kaori/Capsule-Network # replace with your own
        api_key: YOUR API KEY # replace with your own
        tags: None
task: classification # segmentation, classification
architect_settings:
        backbone:
                name: resnet-s
                is_backbone: false
                is_full: false
                is_pretrained: false
                is_freeze: false
        head:
                n_cls: 100
                n_layers: 1
                n_emb: 512
                is_caps: true
                caps:
                        pooling: avg
                        cap_style: c # c: by channel, hw: by height and width
                        reduce: None
                        cap_dims: 4
                        routing:
                                type: em
                                iters: 3
                                temp: 1.5
dataset_settings:
        name: CIFAR100-feats # VOC2012, LungCT-Scan, CIFAR10, CIFAR100, Caltech101, CIFAR10-feats
        path: data/CIFAR100-features
        img_size: 224
training_settings: 
        gpu_ids: [1]
        n_gpu: 1
        loss: ce
        metric: accuracy # dice, accuracy
        ckpt_path: "./mode/test"
        n_epoch: 100
        n_batch: 64
        num_workers: 0
        optimizer: adam
        lr_scheduler: step
        early_stopping: true
        lr: 0.001
        lr_step: 5
        lr_decay: 0.8
        momentum: 0.9
        weight_decay: 0.005