logger:
        project: kaori/Capsule-Network # replace with your own
        api_key: YOUR API KEY # replace with your own
        tags: None
task: classification
architect_settings:
        name: classifier-test
        backbone:
                name: resnet-s
                is_full: false
                is_pretrained: True
                is_freeze: false
        n_cls: 200
        is_caps: false
        caps:
                mode: 1
                cap_dims: 4
                routing:
                        type: dynamic # fuck duck fucak fyucka cyuflkc fyucl fuckl fuycl 
                        params: [3, 1.5]
dataset_settings:
        name: CUB2011
        path: data/CUB_200_2011
        img_size: 224
training_settings: 
        gpu_ids: [0]
        n_gpu: 1
        loss: nll
        metric: accuracy
        ckpt_path: "./mode/test"
        n_epoch: 50
        n_batch: 64
        num_workers: 0
        optimizer: adam
        lr_scheduler: step
        early_stopping: false
        lr: 0.0001
        lr_step: 10
        lr_decay: 0.8
        momentum: 0.9
        weight_decay: 0.005